version: "3.3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /data/grafana-storage/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - 9090:9090
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: always

  prometheus-push-gateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    volumes:
      - prometheus-storage:/prometheus-pushgateway
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /data/grafana-storage/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /data/grafana-storage/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
    restart: always

  sensor-gateway:
    build:
      context: ./sensor-gateway
      dockerfile: Dockerfile
      network: host
    image: sensor-gateway:latest
    ports:
      - "9500:9500"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  grafana-storage:
  prometheus-storage:
