version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /data/grafana-storage/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    volumes:
      - /data/grafana-storage/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /data/grafana-storage/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    links:
      - prometheus