# This is a basic workflow to help you get started with Actions

name: Web Deploy

on:
  push:
    branches: ['master']
    paths:
      - 'homepage/thornton-homepage/**'
      - '.github/workflows/deploy-web.yml'

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy web server container
        run: |
          (docker stop weeb-server && docker rm /weeb-server) || true
          cd ./homepage/thornton-homepage
          docker image prune
          docker build -t weeb:latest --network=host .
          docker run -d -p 3500:3000 --name weeb-server weeb:latest