# This is a basic workflow to help you get started with Actions

name: Web Deploy

on:
  push:
    branches: ['master']
    paths:
      - 'homepage/thornton-homepage/**'
      - '.github/workflows/deploy-web.yml'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Deploy web server container
        run: |
          docker stop weeb-server
          docker build -t weeb:latest
          docker run -d -p 3500:3000 --name weeb-server weeb:latest